GET http://localhost:4000/accounts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MzA1YWE2NjUzMGRiYzI0YWVlOTk4NjUiLCJpZCI6IjYzMDVhYTY2NTMwZGJjMjRhZWU5OTg2NSIsImlhdCI6MTY2MTMxODczMSwiZXhwIjoxNjYxMzE5NjMxfQ.WXHW_nNw5nXY6HRxAbV_5ueQj9_3qGOBmDkmrDTyWrY